FROM php:8.5-fpm-alpine

RUN apk add --no-cache \
        bash \
        git \
        unzip \
        icu-dev \
        sqlite \
        sqlite-dev \
    && docker-php-ext-install intl pdo_sqlite

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /app

EXPOSE 9000
CMD ["php-fpm", "-F"]
